### PR TITLE
update for new Images: now images are just arrays, and I've permuted …

### PR DESCRIPTION
**Pull request by dlfivefifty**
…the dimensions so the output is correct

### CODE REVIEW

**Comment by ehkropf** [comment]
Thanks! I'll double check and merge this before the end of the day, provided nothing unexpected comes up. ;)

**Comment by ehkropf** [comment]
Running the sample code in the docs shows the orientation is wrong in the image output (x and y completely flipped?). The zeros and poles are in the wrong place. I unfortunately don't have time to chase it down right now. :( Check code below (compare with images on doc page).

```julia
using Images
using ComplexPhasePortrait

nx = 1000
x = linspace(-1, 1, nx)
Z = x' .+ flipdim(x, 1)*im

f(z) = (z - 0.5im).^2.*(z + 0.5+0.5im)./z
fz = f(Z)

img = portrait(fz)
```

If you have a different set of commands to get the proper orientation with your commit, the documentation could be changed to match.

**Comment by dlfivefifty** [comment]
Ah OK that can be corrected.

**Comment by dlfivefifty** [comment]
it should be fixed now

**Comment by ehkropf** [comment]
Thanks!

**Pull request merged**
