### PR TITLE
Compat entries; GH actions; closes #10, closes #13, closes #14

### PR DESCRIPTION
**Pull request by jagot**
I updated all pertinent compat bounds and transitioned CI to Github Actions. I had to drop Julia 1.3 due to https://github.com/JuliaPlots/Makie.jl/issues/904.

### CODE REVIEW

**Comment by devmotion** [comment]
I opened a [PR](https://github.com/JuliaPlots/AbstractPlotting.jl/pull/687) that fixes the compilation error of AbstractPlotting, so maybe it is not necessary to drop support for Julia 1.3.

**Comment by jagot** [comment]
Bump 🙂

**Comment by jagot** [comment]
@ehkropf @dlfivefifty Does this look good enough?

**Comment by dlfivefifty** [comment]
Sorry missed this before! Will merge and tag now

**Pull request merged**
